items:
  enableamountlimit: true
  silentamountlimit: true
  maxspawnamount: 20
tpa:
  expiration: 30
broadcasting:
  effectId: 42069
  # In Milliseconds (1000 for 1 second)
  defaultBroadcastDuration: 5000
  timeLimit: 25000
  repeatingInterval: 30000
  repeatingDuration: 6000
  repeatingMessages:
    - SupahBroadcasto
    - This is bla b
    - a a a 
afkchecker:
  enabled: true
  timeout: 600
  # announceAFK will just tell everyone when someone goes afk. kickAFK will get kick players that go afk.
  announceAFK: true
  kickAFK: false
teleportation:
  # Delay in seconds before players can teleport (through warp, tpa, etc)
  delay: 5
  cancelOnMove: true
  cancelOnDamage: true
autorefuel:
  # Fuel percentage threshold to trigger auto-refuel (default: 80%)
  threshold: 80
  # Check interval in milliseconds (default: 5000 = 5 seconds)
  checkInterval: 5000
autorepair:
  # Health percentage threshold to trigger auto-repair (default: 90%)
  threshold: 90
  # Check interval in milliseconds (default: 5000 = 5 seconds)
  checkInterval: 5000
autorepairitems:
  # Quality percentage threshold to trigger auto-repair (default: 90%)
  threshold: 90
  # Check interval in milliseconds (default: 5000 = 5 seconds)
  checkInterval: 5000
autoammo:
  # Ammo amount threshold to trigger auto-refill (default: 80%)
  threshold: 80  # Will refill magazines when below 80% of capacity
  # Gun magazine threshold to trigger auto-refill (default: 80% - more aggressive)
  gunThreshold: 80
  # Check interval in milliseconds (default: 2000 = 2 seconds)
  checkInterval: 1000  # Check every 1 second instead of 2 seconds for faster response
connections:
  joinMessages: true
  leaveMessages: true
